"""Finance's departmental drafting agent.

Read scope: classification, customers. Write scope: drafts. Deliberately
does NOT get timeline or raw_evidence scope (SPEC-postmortem.md section
6; ARCHITECTURE.md section 2's diagram: "windows + terms only, timeline
detail DENIED"). downtime_windows already live on Classification -
duplicated there by Classifier precisely so Exposure never needs
Timeline scope to get them - so the attempted Timeline read below exists
purely to prove the boundary is real, same reasoning and same audit-log
proof as Comms' and Compliance's raw_evidence reads (see comms.py).

Design choice: the exposure dollar figures are computed deterministically
in Python from Classification and Customer data (_compute_credit below),
not generated by the model. A finance number a judge can trace to its
inputs is worth more than one an LLM asserts. The model is only asked to
phrase a short prose summary of numbers it is *given* - explicitly told
not to recompute or alter them - which keeps this agent behind the same
Model Armor gate (and the same blocked-path behavior) as the other three
departmental agents rather than skipping the gateway entirely.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

from pydantic import BaseModel

from agents.contracts import RunResult
from data import scope_store
from data.models import Collection, Envelope, OrgClaim, SlaExposureDraft, new_id, now
from gateway import agent_gateway

logger = logging.getLogger("mortemtrace.exposure")

_MONTH_HOURS = 30 * 24.0  # hackathon-grade approximation of hours per month


class _ExposureSummaryOutput(BaseModel):
    body: str


def run(claim: OrgClaim, envelope: Envelope) -> RunResult:
    incident_id = envelope.incident_id or envelope.payload.get("incident_id")
    if not incident_id:
        return RunResult(status="dead_letter", detail="envelope carried no incident_id")

    # Exposure's registry scope is windows + customer terms only - it
    # never gets Timeline. Demo-only: deliberately walk into that boundary
    # so the denial is visible in /audit (SPEC section 10, beat 2). Gated
    # behind MORTEMTRACE_DEMO_SCOPE_PROOFS so production does not pay a
    # registry lookup plus an audit write per run for a proof nobody is
    # watching. The boundary holds either way.
    scope_store.demo_scope_proof(claim, Collection.TIMELINE, incident_id)

    classification = scope_store.read(claim, Collection.CLASSIFICATION, incident_id)
    if not classification:
        return RunResult(status="dead_letter", detail="no classification record found for incident")

    services = set(classification.get("services", []))
    # Firestore's array-contains-any isn't in scope_store's fake yet
    # (tests/fakes.py's _match() supports only ==, in, array_contains),
    # so the services intersection is done client-side rather than
    # assuming a query operator that may not exist.
    customers = scope_store.try_query(claim, Collection.CUSTOMERS, filters=[])
    matched = [c for c in customers if services & set(c.get("services_subscribed", []))]

    total_downtime_hours = sum(_window_hours(w) for w in classification.get("downtime_windows", []))
    exposure_by_customer = {
        customer["customer_id"]: _compute_credit(customer, total_downtime_hours)
        for customer in matched
    }

    prompt = _build_prompt(incident_id, total_downtime_hours, matched, exposure_by_customer)

    agent, outcome = agent_gateway.build_agent(
        name=claim.agent_name, run_id=claim.run_id, org_id=claim.org_id,
        instruction=(
            "You are the Finance department's SLA exposure drafting "
            "assistant. You are given already-computed SLA credit "
            "exposure figures per customer. Write a short factual summary "
            "of the exposure for a finance audience. Do not recompute, "
            "invent, or alter any number - repeat exactly the figures "
            "given. Return JSON matching the schema."
        ),
        output_schema=_ExposureSummaryOutput,
    )
    result = agent_gateway.invoke(agent, prompt, run_id=claim.run_id, org_id=claim.org_id)
    if outcome.blocked:
        return RunResult(status="blocked", detail=outcome.block_reason,
                          turns=result.turns, tokens_used=result.tokens_used)

    try:
        parsed = _ExposureSummaryOutput.model_validate_json(result.text)
    except ValueError as exc:
        return RunResult(status="dead_letter",
                          detail=f"exposure summary output failed schema validation: {exc}",
                          turns=result.turns, tokens_used=result.tokens_used)

    # Claimed after the model call, not before - see
    # scope_store.claim_idempotency_key's docstring. Guards against a
    # redelivered timeline.committed (the six-way departmental fan-out can
    # outrun the Pub/Sub ack deadline) writing a second, independent draft.
    if not scope_store.claim_idempotency_key(
        claim, Collection.DRAFTS, f"exposure:{claim.run_id}:{incident_id}",
    ):
        logger.info(
            "exposure: run %s for incident %s already has a draft "
            "(likely a Pub/Sub redelivery) - not writing a duplicate",
            claim.run_id, incident_id,
        )
        return RunResult(status="ok", turns=result.turns, tokens_used=result.tokens_used)

    draft = SlaExposureDraft(
        draft_id=new_id("draft"),
        incident_ref=incident_id,
        org_id=claim.org_id,
        body=parsed.body,
        exposure_by_customer=exposure_by_customer,
        # Exposure can't cite timeline detail - it isn't in scope - so
        # the classification record it did read is the source of record.
        source_refs=[f"classification:{incident_id}"],
    )
    scope_store.write(claim, Collection.DRAFTS, draft.draft_id, draft.model_dump(mode="json"))
    logger.info("sla exposure draft %s written for incident %s", draft.draft_id, incident_id)
    return RunResult(status="ok", turns=result.turns, tokens_used=result.tokens_used)


def _window_hours(window: dict) -> float:
    start = _parse_dt(window.get("start"))
    if start is None:
        return 0.0
    end = _parse_dt(window.get("end")) or now()
    return max((end - start).total_seconds() / 3600.0, 0.0)


def _parse_dt(value) -> Optional[datetime]:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None


def _compute_credit(customer: dict, total_downtime_hours: float) -> float:
    """Hackathon-grade heuristic, deliberately simple and traceable to its
    inputs rather than accurate finance modelling: convert the customer's
    uptime_target into an allowed-downtime budget over an approximate
    720-hour month, and if this incident's total downtime burned through
    more than that budget, credit the breach hours at the customer's
    contracted credit_rate. Customers whose downtime stayed within their
    SLA's allowance still appear in the result at $0 - they were affected
    by the incident, they just weren't breached.
    """
    sla_terms = customer.get("sla_terms") or {}
    uptime_target = sla_terms.get("uptime_target", 1.0)
    credit_rate = sla_terms.get("credit_rate", 0.0)

    allowed_downtime_hours = (1.0 - uptime_target) * _MONTH_HOURS
    breach_hours = max(total_downtime_hours - allowed_downtime_hours, 0.0)
    return round(breach_hours * credit_rate, 2)


def _build_prompt(incident_id: str, total_downtime_hours: float,
                   matched: list[dict], exposure_by_customer: dict[str, float]) -> str:
    lines = [f"Incident: {incident_id}", f"Total downtime: {total_downtime_hours:.2f} hours", ""]
    if not matched:
        lines.append("No customers are subscribed to the affected services.")
    else:
        lines.append("Computed SLA credit exposure by customer:")
        for customer in matched:
            amount = exposure_by_customer.get(customer["customer_id"], 0.0)
            lines.append(f"- {customer.get('name', customer['customer_id'])}: ${amount:.2f}")
    lines.append("")
    lines.append("Write a brief factual summary body using exactly these figures. Return JSON matching the schema.")
    return "\n".join(lines)
